### ISSUE TITLE
Maven Dependency issue

### ISSUE THREAD

**Issue by bstienstra** [bigmlcom/histogram#68] opened 2022-12-14 17:34 UTC
I've been using your library for a while, but I can no longer pull your library from Maven.   I have not built this project for about a year. 
 I need to build a new version but I cannot build it anymore because it cannot locate your library anymore.  I tried 4.1.3 and 4.1.4 and they have the same problem

In my .pom file I have 
		&#60;dependency>
			&#60;groupId>bigml&#60;/groupId>
			&#60;artifactId>histogram&#60;/artifactId>
			&#60;version>4.1.4&#60;/version>
		&#60;/dependency>
...
	&#60;repositories>
		&#60;repository>
			&#60;id>Clojars.repository&#60;/id>
			&#60;url>http://clojars.org/repo/&#60;/url>
		&#60;/repository>
	&#60;/repositories>
	
In Jenkins I can see it getting the histogram-4.1.4.pom from the clojars repo, but then it gets the same file from repo.maven.apache.org which does not exist, then I get an error about a different repo. ( See output below)

Jenkins OUTPUT:
          Downloading: http://clojars.org/repo/bigml/histogram/4.1.4/histogram-4.1.4.pom
          Downloading: https://repo.maven.apache.org/maven2/bigml/histogram/4.1.4/histogram-4.1.4.pom	
          ...
          Failed to read artifact descriptor for bigml:histogram:jar:4.1.4: Could not transfer artifact bigml:histogram:pom:4.1.4 from/to jboss (https://repository.jboss.org/nexus/content/groups/public-jboss): Received fatal alert: internal_error -> [Help 1]

This is one of many libraries I'm using and all the others are pulling fine.  I think there is a problem with your maven setup.  Can you please advise me on what to do to fix this?

**Comment by bstienst** [comment] 2023-01-03 16:37
The problem is the repo name changed from 

https://clojars.org/repo/

to 

https://repo.clojars.org/

and your pom file still references https://clojars.org/repo/

My build environment will not allow redirects while building releases.

**Comment by jaor** [comment] 2023-01-03 17:11
@bstienst i am not sure i understand.  as far as i can tell, we use in our pom repo.clojars.org [here](https://github.com/bigmlcom/histogram/blob/master/pom.xml#L72). did you mean it the other way round?

**Comment by bstienst** [comment] 2023-01-03 20:53
From https://repo.clojars.org/bigml/histogram/4.1.3/histogram-4.1.3.pom

<repositories>
<repository>
<id>central</id>
<url>https://repo1.maven.org/maven2/</url>
<snapshots>
<enabled>false</enabled>
</snapshots>
<releases>
<enabled>true</enabled>
</releases>
</repository>
<repository>
<id>clojars</id>
*<url>https://clojars.org/repo/ <https://clojars.org/repo/></url>*
<snapshots>
<enabled>true</enabled>
</snapshots>
<releases>
<enabled>true</enabled>
</releases>
</repository>
</repositories>

But I see that you also released 4.1.4, and it uses the correct repo.

I could have sworn I checked for a new version.

Sorry, you can close this issue.

Brian

**Closed** 2023-01-03 21:20 UTC
